 CREATE TABLE IF NOT EXISTS likes (
  user INT NOT NULL,
  beer INT NOT NULL,
  PRIMARY KEY (user, beer),
  FOREIGN KEY (user) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (beer) REFERENCES beer(id) ON UPDATE CASCADE ON DELETE CASCADE
);
