 CREATE TABLE IF NOT EXISTS user_like (
  user_id INT NOT NULL,
  beer_id INT NOT NULL,
  PRIMARY KEY (user_id, beer_id),
  FOREIGN KEY (user_id) REFERENCES user(id) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (beer_id) REFERENCES beer(id) ON UPDATE CASCADE ON DELETE CASCADE
);
