 CREATE TABLE IF NOT EXISTS user_like (
  user VARCHAR(20) NOT NULL,
  beer_id INT NOT NULL,
  PRIMARY KEY (user, beer_id),
  FOREIGN KEY (user) REFERENCES user(username) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (beer_id) REFERENCES beer(id) ON UPDATE CASCADE ON DELETE CASCADE
);
